#Last Updated: September 23, 2013
#Description: This is an R script that performs all of the statistics in the paper. 

require("car") #This needs to be uploaded to use the stats functions that are used. 

#This the location of the stats_data.csv file with the data for OUR dataset that was generated by the analysis scripts
data = read.delim("/Users/Eleisha/Documents/Wilke_Lab/Project_1/project/r_scripts/stats_data.csv")

head(data)

head(data$mean_entropy_temp_0.0)

fixed_natural_ttest = t.test(data$mean_entropy_temp_0.0,  data$mean_entropy_natural, paired = TRUE)
print(fixed_natural_ttest)

designed_003_natural_ttest = t.test(data$mean_entropy_temp_0.03,  data$mean_entropy_natural, paired = TRUE)
print(designed_003_natural_ttest)

designed_01_natural_ttest = t.test(data$mean_entropy_temp_0.1,  data$mean_entropy_natural, paired = TRUE)
print(designed_01_natural_ttest)

cor_ttest = t.test(data$cor_entropy_RSA_03, data$natural_cor_entropy_RSA_value, paired = TRUE)
print(cor_ttest)

#This the location of the stats_data_noah.csv file with the data for the UCSF dataset that was generated by the analysis scripts
data4 = read.delim("/Users/Eleisha/Documents/Wilke_Lab/Project_1/project/r_scripts/stats_data_noah.csv")

head(data4)
head(data4$mean_entropy_temp_0.0)

fixed_natural_ttest2 = t.test(data4$mean_entropy_temp_0.0,  data4$mean_entropy_natural, paired = TRUE)
print(fixed_natural_ttest2)

designed_09_natural_ttest = t.test(data4$mean_entropy_temp_0.9,  data4$mean_entropy_natural, paired = TRUE)
print(designed_09_natural_ttest)

designed_12_natural_ttest = t.test(data4$mean_entropy_temp_1.2,  data4$mean_entropy_natural, paired = TRUE)
print(designed_12_natural_ttest)


cor_ttest2 = t.test(data4$cor_entropy_RSA_03, data4$natural_cor_entropy_RSA_value, paired = TRUE)
print(cor_ttest2)

#Performs the Brown-Forsythe Test for Variance 
BFData_06 = c(data$mean_entropy_temp_0.6,  data$mean_entropy_natural)
group_06 =  as.factor(c(rep("Temp0.6", length(data$mean_entropy_temp_0.6)), rep("Natural", length(data$mean_entropy_natural))))
data06 = data.frame(source=group_06, mean_entropy=BFData_06)
BF_06 = leveneTest(mean_entropy ~ source, data=data06)
print(BF_06)

#Performs the Brown-Forsythe Test for Variance 
BFData_09 = c(data$mean_entropy_temp_0.9,  data$mean_entropy_natural)
group_09 =  as.factor(c(rep("Temp0.9", length(data$mean_entropy_temp_0.9)), rep("Natural", length(data$mean_entropy_natural))))
data09 = data.frame(source=group_09, mean_entropy=BFData_09)
BF_09 = leveneTest(mean_entropy ~ source, data=data09)
print(BF_09)

#This the location of the mixed_stats_data.csv file with the data for the UCSF dataset that was generated by the analysis scripts
data2 = read.delim("/Users/Eleisha/Documents/Wilke_Lab/Project_1/project/r_scripts/mixed_duncan_stats_file.csv")
head(data2)
cor_ttest_mix1 = t.test(data2$cor_entropy_00_01, data2$natural_cor_entropy_value, paired = TRUE)
print(cor_ttest_mix1)

cor_ttest_mix2 = t.test(data2$cor_entropy_003_01, data2$natural_cor_entropy_value, paired = TRUE)
print(cor_ttest_mix2)

#This the location of the mixed_noah_stats_data.csv file with the data for the UCSF dataset that was generated by the analysis scripts
data3 = read.delim("/Users/Eleisha/Documents/Wilke_Lab/Project_1/project/r_scripts/mixed_noah_stats_file.csv")
head(data3)
cor_ttest_mix3 = t.test(data3$cor_entropy_03_18, data3$natural_cor_entropy_value, paired = TRUE)
print(cor_ttest_mix3)

cor_ttest_mix4 = t.test(data3$cor_entropy_06_18, data3$natural_cor_entropy_value, paired = TRUE)
print(cor_ttest_mix4)



